$$ WIP $$

In [1]:
from treeModels import *
from sklearn.tree import DecisionTreeClassifier as SkDecisionTree
from sklearn.ensemble import RandomForestClassifier as SkRandomForest
import numpy as np
import pandas as pd
import os
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv(os.path.join(os.getenv('workspaceFolder'),'play_tennis.csv'))
df[df['outlook'] == 'Overcast']

outlook  temp humidity    wind play
2   Overcast   Hot     High    Weak  Yes
6   Overcast  Cool   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
14  Overcast   Hot     High  Strong   No
15  Overcast  Mild     High  Strong  Yes
16  Overcast  Mild   Normal    Weak  Yes

In [3]:
X = df.drop("play", axis=1)
Y = df['play']

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [6]:
X_test

outlook  temp humidity    wind
0      Sunny   Hot     High    Weak
11  Overcast  Mild     High  Strong
7      Sunny  Mild     High    Weak
9       Rain  Mild   Normal    Weak

In [6]:
model = DecisionTreeClassifier()
model.fit(X_train, Y_train)

In [7]:
model.get_depth()

5

In [9]:
print(model.tree)

 | 0
....Overcast | 1
........Cool | Yes
........Hot | 3
............Strong | No
............Weak | Yes
........Mild | Yes
....Rain | 3
........Strong | 1
............Cool | No
............Mild | Yes
........Weak | Yes
....Sunny | 2
........High | No
........Normal | Yes



In [11]:
model.predict_proba(['Rain', 'Hot', 'Normal', 'Strong'])

array([0.66666667, 0.33333333])

In [10]:
model.score(X_test, Y_test)

0.75

In [13]:
model.tree.forest['Rain'].forest['Strong'].get_class_proportion()

array([0.66666667, 0.33333333])

In [23]:
skmodel = SkDecisionTree(criterion='entropy')
skmodel.fit(X, Y)

ValueError: could not convert string to float: 'Sunny'

In [24]:
mod = DecisionTreeClassifier()
mod.fit(X, Y)

DecisionTreeClassifier(max_depth=inf, min_samples_split=2, min_samples_leaf=1, min_impurity_decrease=0.0, algorithm='ID3')

In [16]:
df2 = pd.read_csv(os.path.join(os.getenv('workspaceFolder'),'CarEval.csv'))
df2

buying  maint  doors persons lug_boot safety class values
0     vhigh  vhigh      2       2    small    low        unacc
1     vhigh  vhigh      2       2    small    med        unacc
2     vhigh  vhigh      2       2    small   high        unacc
3     vhigh  vhigh      2       2      med    low        unacc
4     vhigh  vhigh      2       2      med    med        unacc
...     ...    ...    ...     ...      ...    ...          ...
1723    low    low  5more    more      med    med         good
1724    low    low  5more    more      med   high        vgood
1725    low    low  5more    more      big    low        unacc
1726    low    low  5more    more      big    med         good
1727    low    low  5more    more      big   high        vgood

[1728 rows x 7 columns]

In [17]:
df2_2 = df2

In [28]:
df2_2 = df2.assign(doors = [int(x) if x != '5more' else 5 for x in df2['doors']])

In [29]:
df2_2 = df2_2.assign(persons = [int(x) if x != 'more' else 6 for x in df2['persons']])

In [30]:
df2_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   buying        1728 non-null   object
 1   maint         1728 non-null   object
 2   doors         1728 non-null   int64 
 3   persons       1728 non-null   int64 
 4   lug_boot      1728 non-null   object
 5   safety        1728 non-null   object
 6   class values  1728 non-null   object
dtypes: int64(2), object(5)
memory usage: 94.6+ KB


In [31]:
df2_2

buying  maint  doors  persons lug_boot safety class values
0     vhigh  vhigh      2        2    small    low        unacc
1     vhigh  vhigh      2        2    small    med        unacc
2     vhigh  vhigh      2        2    small   high        unacc
3     vhigh  vhigh      2        2      med    low        unacc
4     vhigh  vhigh      2        2      med    med        unacc
...     ...    ...    ...      ...      ...    ...          ...
1723    low    low      5        6      med    med         good
1724    low    low      5        6      med   high        vgood
1725    low    low      5        6      big    low        unacc
1726    low    low      5        6      big    med         good
1727    low    low      5        6      big   high        vgood

[1728 rows x 7 columns]

In [5]:
df2['doors'] = str(df2['doors'])
df2['persons'] = str(df2['persons'])

In [32]:
X = df2.drop('class values', axis=1)
Y = df2['class values']

In [33]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25)

In [34]:
model = DecisionTreeClassifier()
model.fit(X_train, Y_train)

E:\Tomas\Desktop\Code\TPFinalAlgo2\src\treeModels\decision_algorithms.py:158: RuntimeWarning: invalid value encountered in scalar divide
  return information_gain(col_values, Y) / si


In [13]:
model.get_depth()

5

In [24]:
model.score(X_test, Y_test)

0.9351851851851852

In [24]:
print(model.tree)

 | 5
....high | 0
........high | 1
............high | 4
................big | acc
................med | acc
................small | acc
............low | 4
................big | acc
................med | acc
................small | acc
............med | 4
................big | acc
................med | acc
................small | acc
............vhigh | unacc
........low | 1
............high | 4
................big | vgood
................med | vgood
................small | acc
............low | 4
................big | vgood
................med | vgood
................small | good
............med | 4
................big | vgood
................med | unacc
................small | good
............vhigh | 4
................big | acc
................med | acc
................small | acc
........med | 1
............high | 4
................big | acc
................med | unacc
................small | acc
............low | 4
................big | vgood
................med | vgood
..........

In [187]:
df

outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No
14  Overcast   Hot     High  Strong   No
15  Overcast  Mild     High  Strong  Yes
16  Overcast  Mild   Normal    Weak  Yes
17      Rain  Mild     High  Strong  Yes
18      Rain  Mild   Normal    Weak   No

In [74]:
X_n = np.array(X)
Y_n = np.array(Y)
X_n, Y_n

(array([['Sunny', 'Hot', 'High', 'Weak'],
        ['Sunny', 'Hot', 'High', 'Strong'],
        ['Overcast', 'Hot', 'High', 'Weak'],
        ['Rain', 'Mild', 'High', 'Weak'],
        ['Rain', 'Cool', 'Normal', 'Weak'],
        ['Rain', 'Cool', 'Normal', 'Strong'],
        ['Overcast', 'Cool', 'Normal', 'Strong'],
        ['Sunny', 'Mild', 'High', 'Weak'],
        ['Sunny', 'Cool', 'Normal', 'Weak'],
        ['Rain', 'Mild', 'Normal', 'Weak'],
        ['Sunny', 'Mild', 'Normal', 'Strong'],
        ['Overcast', 'Mild', 'High', 'Strong'],
        ['Overcast', 'Hot', 'Normal', 'Weak'],
        ['Rain', 'Mild', 'High', 'Strong'],
        ['Overcast', 'Hot', 'High', 'Strong'],
        ['Overcast', 'Mild', 'High', 'Strong'],
        ['Overcast', 'Mild', 'Normal', 'Weak'],
        ['Rain', 'Mild', 'High', 'Strong'],
        ['Rain', 'Mild', 'Normal', 'Weak']], dtype=object),
 array(['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes',
        'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 

In [119]:
i = [i for i in range(len(X_n))]
i

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

In [120]:
rnd = []
y_rnd = []
for ind in np.random.choice(i, 30, True):
    rnd.append(X_n[ind])
    y_rnd.append(Y_n[ind])
rnd = np.array(rnd)
y_rnd = np.array(y_rnd)
rnd, y_rnd

(array([['Rain', 'Mild', 'High', 'Strong'],
        ['Rain', 'Cool', 'Normal', 'Strong'],
        ['Overcast', 'Hot', 'Normal', 'Weak'],
        ['Rain', 'Cool', 'Normal', 'Strong'],
        ['Overcast', 'Mild', 'High', 'Strong'],
        ['Overcast', 'Mild', 'Normal', 'Weak'],
        ['Sunny', 'Hot', 'High', 'Weak'],
        ['Overcast', 'Mild', 'Normal', 'Weak'],
        ['Overcast', 'Mild', 'Normal', 'Weak'],
        ['Overcast', 'Hot', 'Normal', 'Weak'],
        ['Rain', 'Cool', 'Normal', 'Strong'],
        ['Overcast', 'Hot', 'High', 'Strong'],
        ['Overcast', 'Hot', 'High', 'Strong'],
        ['Overcast', 'Hot', 'High', 'Weak'],
        ['Overcast', 'Mild', 'High', 'Strong'],
        ['Sunny', 'Mild', 'Normal', 'Strong'],
        ['Rain', 'Mild', 'High', 'Weak'],
        ['Sunny', 'Mild', 'High', 'Weak'],
        ['Sunny', 'Cool', 'Normal', 'Weak'],
        ['Overcast', 'Mild', 'High', 'Strong'],
        ['Overcast', 'Mild', 'High', 'Strong'],
        ['Rain', 'Mild', 'High

In [128]:
i = [i for i in range(X_n.shape[1])]
i

[0, 1, 2, 3]

In [183]:
fea = np.sort(np.random.choice(i, 2, False))
fea

array([0, 3])

In [184]:
samples = np.array([rnd[:,index] if index in fea else np.array(['' for index in range(rnd.shape[0])]) for index in i]).T
samples

array([['Rain', '', '', 'Strong'],
       ['Rain', '', '', 'Strong'],
       ['Overcast', '', '', 'Weak'],
       ['Rain', '', '', 'Strong'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Weak'],
       ['Sunny', '', '', 'Weak'],
       ['Overcast', '', '', 'Weak'],
       ['Overcast', '', '', 'Weak'],
       ['Overcast', '', '', 'Weak'],
       ['Rain', '', '', 'Strong'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Weak'],
       ['Overcast', '', '', 'Strong'],
       ['Sunny', '', '', 'Strong'],
       ['Rain', '', '', 'Weak'],
       ['Sunny', '', '', 'Weak'],
       ['Sunny', '', '', 'Weak'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Strong'],
       ['Rain', '', '', 'Weak'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Weak'],
       ['Sunny', '', '', 'Strong'],
       ['R

In [185]:
m = DecisionTreeClassifier()
m.fit(samples, y_rnd)
print(m.tree)

 | 0
....Overcast | 3
........Strong | Yes
........Weak | Yes
....Rain | 3
........Strong | No
........Weak | Yes
....Sunny | 3
........Strong | Yes
........Weak | No



In [186]:
m.score(samples, y_rnd)

0.8333333333333334

In [264]:
X.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety'], dtype='object')

In [10]:
mod = RandomForestClassifier(max_features=None)
mod.fit(X_train, Y_train)

model = DecisionTreeClassifier()
model.fit(X_train, Y_train)

In [11]:
mod.score(X_test, Y_test), model.score(X_test, Y_test)

(0.7777777777777778, 0.7754629629629629)

In [12]:
i = 330
mod.predict_proba(np.array(X_test)[i]), model.predict_proba(np.array(X_test)[i])

(array([0.56018659, 0.        , 0.43981341, 0.        ]),
 array([0.55555556, 0.        , 0.44444444, 0.        ]))

In [13]:
model.tree.classes

array(['acc', 'good', 'unacc', 'vgood'], dtype=object)

In [14]:
np.array(Y_test)[i]

'acc'

In [15]:
Y

0       unacc
1       unacc
2       unacc
3       unacc
4       unacc
        ...  
1723     good
1724    vgood
1725    unacc
1726     good
1727    vgood
Name: class values, Length: 1728, dtype: object

In [16]:
print(mod.forest[0].tree)

 | 5
....high | 0
........high | 1
............high | 4
................big | acc
................med | acc
................small | acc
............low | 4
................big | acc
................med | unacc
................small | unacc
............med | 4
................big | unacc
................med | acc
................small | acc
............vhigh | unacc
........low | 1
............high | 4
................big | vgood
................med | unacc
................small | acc
............low | 4
................big | vgood
................med | vgood
................small | good
............med | 4
................big | vgood
................med | vgood
................small | good
............vhigh | 4
................big | acc
................med | acc
................small | acc
........med | 1
............high | 4
................big | acc
................med | acc
................small | acc
............low | 4
................big | vgood
................med | vgood
......

In [17]:
from collections import Counter

In [18]:
Counter([tree.predict(np.array(X)[0]).item() for tree in mod.forest]).most_common(1)[0][0]

'unacc'

In [3]:
n = np.array([5, 2, 4])
n[np.argsort(n)]

array([2, 4, 5])

In [6]:
len(n[0])

TypeError: object of type 'numpy.int32' has no len()

In [2]:
df2 = pd.read_csv(os.path.join(os.getenv('workspaceFolder'),'star_classification.csv'))
df2

obj_ID       alpha      delta         u         g         r  \
0      1.237661e+18  135.689107  32.494632  23.87882  22.27530  20.39501   
1      1.237665e+18  144.826101  31.274185  24.77759  22.83188  22.58444   
2      1.237661e+18  142.188790  35.582444  25.26307  22.66389  20.60976   
3      1.237663e+18  338.741038  -0.402828  22.13682  23.77656  21.61162   
4      1.237680e+18  345.282593  21.183866  19.43718  17.58028  16.49747   
...             ...         ...        ...       ...       ...       ...   
99995  1.237679e+18   39.620709  -2.594074  22.16759  22.97586  21.90404   
99996  1.237679e+18   29.493819  19.798874  22.69118  22.38628  20.45003   
99997  1.237668e+18  224.587407  15.700707  21.16916  19.26997  18.20428   
99998  1.237661e+18  212.268621  46.660365  25.35039  21.63757  19.91386   
99999  1.237661e+18  196.896053  49.464643  22.62171  21.79745  20.60115   

              i         z  run_ID  rerun_ID  cam_col  field_ID   spec_obj_ID  \
0      19.16573  18.79371    3606       301        2        79  6.543777e+18   
1      21.16812  21.61427    4518       301        5       119  1.176014e+19   
2      19.34857  18.94827    3606       301        2       120  5.152200e+18   
3      20.50454  19.25010    4192       301        3       214  1.030107e+19   
4      15.97711  15.54461    8102       301        3       137  6.891865e+18   
...         ...       ...     ...       ...      ...       ...           ...   
99995  21.30548  20.73569    7778       301        2       581  1.055431e+19   
99996  19.75759  19.41526    7917       301        1       289  8.586351e+18   
99997  17.69034  17.35221    5314       301        4       308  3.112008e+18   
99998  19.07254  18.62482    3650       301        4       131  7.601080e+18   
99999  20.00959  19.28075    3650       301        4        60  8.343152e+18   

        class  redshift  plate    MJD  fiber_ID  
0      GALAXY  0.634794   5812  56354       171  
1      GALAXY  0.779136  10445  58158       427  
2      GALAXY  0.644195   4576  55592       299  
3      GALAXY  0.932346   9149  58039       775  
4      GALAXY  0.116123   6121  56187       842  
...       ...       ...    ...    ...       ...  
99995  GALAXY  0.000000   9374  57749       438  
99996  GALAXY  0.404895   7626  56934       866  
99997  GALAXY  0.143366   2764  54535        74  
99998  GALAXY  0.455040   6751  56368       470  
99999  GALAXY  0.542944   7410  57104       851  

[100000 rows x 18 columns]

In [3]:
df2_2 = df2.assign(quality = [str(x) for x in df2['cam_col']]).sample(1000)
df2_2

obj_ID       alpha      delta         u         g         r  \
86155  1.237655e+18  129.643686  43.552072  21.77560  20.64049  20.76442   
33290  1.237679e+18   26.011033   1.102870  24.63467  22.92527  20.06686   
89351  1.237663e+18  243.767702  22.239698  23.98924  22.39429  20.67818   
95564  1.237662e+18  248.832880  31.410020  23.49327  20.76472  19.79869   
32830  1.237659e+18  220.684552  49.100323  20.23194  18.37549  17.52183   
...             ...         ...        ...       ...       ...       ...   
19952  1.237659e+18  251.905090  34.796515  21.09601  19.99323  19.57964   
13578  1.237661e+18  220.399066  40.806342  25.15149  20.79975  19.12770   
91758  1.237673e+18  354.959461   6.803469  23.83047  24.34033  21.91968   
27432  1.237655e+18  139.412861  -2.226604  25.70571  21.35263  20.77316   
77160  1.237679e+18   43.399509  -3.144893  23.08829  22.42616  20.68871   

              i         z  run_ID  rerun_ID  cam_col  field_ID   spec_obj_ID  \
86155  20.68707  20.40918    2243       301        2        92  9.322516e+18   
33290  19.76221  22.82690    7717       301        1       503  8.829318e+18   
89351  19.82826  19.34577    4010       301        5       204  4.422598e+18   
95564  19.35197  18.93721    3918       301        6       340  1.228815e+19   
32830  17.13030  16.81606    3180       301        3       100  1.178861e+18   
...         ...       ...     ...       ...      ...       ...           ...   
19952  19.35253  19.41785    3225       301        4       278  1.228146e+19   
13578  18.50516  18.08265    3699       301        2       195  5.823305e+18   
91758  20.29804  19.61527    6354       301        2       296  6.936760e+18   
27432  20.50333  20.33375    2188       301        2       116  4.240202e+18   
77160  19.64704  19.14791    7865       301        5       204  4.887624e+18   

        class  redshift  plate    MJD  fiber_ID quality  
86155     QSO  2.436402   8280  57061       235       2  
33290    STAR -0.000079   7842  56899        41       1  
89351  GALAXY  0.490650   3928  55331       229       5  
95564     QSO  0.401757  10914  58257       283       6  
32830  GALAXY  0.049388   1047  52733       158       3  
...       ...       ...    ...    ...       ...     ...  
19952    STAR -0.000570  10908  58392       514       4  
13578  GALAXY  0.389682   5172  56071       546       2  
91758  GALAXY  0.695415   6161  56238       331       2  
27432    STAR  0.000583   3766  55213       228       2  
77160  GALAXY  0.539508   4341  55538       335       5  

[1000 rows x 19 columns]

In [4]:
X = df2_2.drop('class', axis=1)
Y = df2_2['class']

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [6]:
from treeModels.decision_algorithms import DecisionAlgorithm

In [28]:
mod = DecisionTreeClassifier(max_depth=10)

In [29]:
mod.fit(X_train, Y_train)

In [30]:
mod.score(X_test, Y_test)

0.965

In [32]:
print(mod.tree)

 | [redshift]
....<=0.005454731500000001 | [delta]
........<=-5.909821380973995 | [spec_obj_ID]
............<=5.78892826610729e+18 | STAR
............>5.78892826610729e+18 | GALAXY
........>-5.909821380973995 | STAR
....>0.005454731500000001 | [redshift]
........<=0.9074847500000001 | [field_ID]
............<=822.0 | [u]
................<=21.46189 | [r]
....................<=19.382985 | [redshift]
........................<=0.2661527 | [alpha]
............................<=258.305890421436 | [fiber_ID]
................................<=534.5 | GALAXY
................................>534.5 | [fiber_ID]
....................................<=539.5 | GALAXY
....................................>539.5 | GALAXY
............................>258.305890421436 | [alpha]
................................<=287.403230982785 | QSO
................................>287.403230982785 | GALAXY
........................>0.2661527 | [delta]
............................<=29.84373078141305 | GALAXY
.............

In [6]:
mod = RandomForestClassifier(n_estimators = 10, max_depth=10, max_features='sqrt')
mod.fit(X_train, Y_train)

E:\Tomas\Desktop\Code\TPFinalAlgo2\src\treeModels\decision_algorithms.py:158: RuntimeWarning: invalid value encountered in scalar divide
  return information_gain(col_values, Y) / split_info(col_values, Y)


In [7]:
mod.score(X_test, Y_test)

0.84

In [14]:
mod.forest[3].tree.samples

array([['', '', '', ..., '', 991, ''],
       ['', '', '', ..., '', 435, ''],
       ['', '', '', ..., '', 299, ''],
       ...,
       ['', '', '', ..., '', 886, ''],
       ['', '', '', ..., '', 573, ''],
       ['', '', '', ..., '', 507, '']], dtype=object)

In [43]:
model = SkDecisionTree()
model.fit(X_train, Y_train)

DecisionTreeClassifier()

In [44]:
model.score(X_test, Y_test)

0.96

In [45]:
model = SkRandomForest(n_estimators=10, max_depth=10)
model.fit(X_train, Y_train)

RandomForestClassifier(max_depth=10, n_estimators=10)

In [46]:
model.score(X_test, Y_test)

0.965

In [47]:
(np.array([1, 2, 5, 6]) <= 5).astype(int)

array([1, 1, 1, 0])

In [48]:
[''] * 5

['', '', '', '', '']