$$ WIP $$

In [1]:
from treeModels import *
from sklearn.tree import DecisionTreeClassifier as SkDecisionTree
from sklearn.ensemble import RandomForestClassifier as SkRandomForest
import numpy as np
import pandas as pd
import os
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv(os.path.join(os.getenv('workspaceFolder'),'play_tennis.csv'))
df[df['outlook'] == 'Overcast']

outlook  temp humidity    wind play
2   Overcast   Hot     High    Weak  Yes
6   Overcast  Cool   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
14  Overcast   Hot     High  Strong   No
15  Overcast  Mild     High  Strong  Yes
16  Overcast  Mild   Normal    Weak  Yes

In [3]:
X = df.drop("play", axis=1)
Y = df['play']

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [6]:
X_test

outlook  temp humidity    wind
0      Sunny   Hot     High    Weak
11  Overcast  Mild     High  Strong
7      Sunny  Mild     High    Weak
9       Rain  Mild   Normal    Weak

In [6]:
model = DecisionTreeClassifier()
model.fit(X_train, Y_train)

In [7]:
model.get_depth()

5

In [9]:
print(model.tree)

 | 0
....Overcast | 1
........Cool | Yes
........Hot | 3
............Strong | No
............Weak | Yes
........Mild | Yes
....Rain | 3
........Strong | 1
............Cool | No
............Mild | Yes
........Weak | Yes
....Sunny | 2
........High | No
........Normal | Yes



In [11]:
model.predict_proba(['Rain', 'Hot', 'Normal', 'Strong'])

array([0.66666667, 0.33333333])

In [10]:
model.score(X_test, Y_test)

0.75

In [13]:
model.tree.forest['Rain'].forest['Strong'].get_class_proportion()

array([0.66666667, 0.33333333])

In [23]:
skmodel = SkDecisionTree(criterion='entropy')
skmodel.fit(X, Y)

ValueError: could not convert string to float: 'Sunny'

In [24]:
mod = DecisionTreeClassifier()
mod.fit(X, Y)

DecisionTreeClassifier(max_depth=inf, min_samples_split=2, min_samples_leaf=1, min_impurity_decrease=0.0, algorithm='ID3')

In [3]:
df2 = pd.read_csv(os.path.join(os.getenv('workspaceFolder'),'CarEval.csv'))
df2

buying  maint  doors persons lug_boot safety class values
0     vhigh  vhigh      2       2    small    low        unacc
1     vhigh  vhigh      2       2    small    med        unacc
2     vhigh  vhigh      2       2    small   high        unacc
3     vhigh  vhigh      2       2      med    low        unacc
4     vhigh  vhigh      2       2      med    med        unacc
...     ...    ...    ...     ...      ...    ...          ...
1723    low    low  5more    more      med    med         good
1724    low    low  5more    more      med   high        vgood
1725    low    low  5more    more      big    low        unacc
1726    low    low  5more    more      big    med         good
1727    low    low  5more    more      big   high        vgood

[1728 rows x 7 columns]

In [9]:
df2['persons'].unique()

array(['2', '4', 'more'], dtype=object)

In [4]:
df2_2 = df2.assign(doors = [int(x) if x != '5more' else 5 for x in df2['doors']])

In [5]:
df2_2 = df2_2.assign(persons = [int(x) if x != 'more' else 6 for x in df2['persons']])

In [14]:
df2_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   buying        1728 non-null   object
 1   maint         1728 non-null   object
 2   doors         1728 non-null   int64 
 3   persons       1728 non-null   int64 
 4   lug_boot      1728 non-null   object
 5   safety        1728 non-null   object
 6   class values  1728 non-null   object
dtypes: int64(2), object(5)
memory usage: 94.6+ KB


In [15]:
df2_2

buying  maint  doors  persons lug_boot safety class values
0     vhigh  vhigh      2        2    small    low        unacc
1     vhigh  vhigh      2        2    small    med        unacc
2     vhigh  vhigh      2        2    small   high        unacc
3     vhigh  vhigh      2        2      med    low        unacc
4     vhigh  vhigh      2        2      med    med        unacc
...     ...    ...    ...      ...      ...    ...          ...
1723    low    low      5        6      med    med         good
1724    low    low      5        6      med   high        vgood
1725    low    low      5        6      big    low        unacc
1726    low    low      5        6      big    med         good
1727    low    low      5        6      big   high        vgood

[1728 rows x 7 columns]

In [5]:
df2['doors'] = str(df2['doors'])
df2['persons'] = str(df2['persons'])

In [6]:
X = df2.drop('class values', axis=1)
Y = df2['class values']

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25)

In [12]:
model = DecisionTreeClassifier()
model.fit(X_train, Y_train)

In [13]:
model.get_depth()

5

In [14]:
model.score(X_train, Y_train)

0.8171296296296297

In [24]:
print(model.tree)

 | 5
....high | 0
........high | 1
............high | 4
................big | acc
................med | acc
................small | acc
............low | 4
................big | acc
................med | acc
................small | acc
............med | 4
................big | acc
................med | acc
................small | acc
............vhigh | unacc
........low | 1
............high | 4
................big | vgood
................med | vgood
................small | acc
............low | 4
................big | vgood
................med | vgood
................small | good
............med | 4
................big | vgood
................med | unacc
................small | good
............vhigh | 4
................big | acc
................med | acc
................small | acc
........med | 1
............high | 4
................big | acc
................med | unacc
................small | acc
............low | 4
................big | vgood
................med | vgood
..........

In [187]:
df

outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No
14  Overcast   Hot     High  Strong   No
15  Overcast  Mild     High  Strong  Yes
16  Overcast  Mild   Normal    Weak  Yes
17      Rain  Mild     High  Strong  Yes
18      Rain  Mild   Normal    Weak   No

In [74]:
X_n = np.array(X)
Y_n = np.array(Y)
X_n, Y_n

(array([['Sunny', 'Hot', 'High', 'Weak'],
        ['Sunny', 'Hot', 'High', 'Strong'],
        ['Overcast', 'Hot', 'High', 'Weak'],
        ['Rain', 'Mild', 'High', 'Weak'],
        ['Rain', 'Cool', 'Normal', 'Weak'],
        ['Rain', 'Cool', 'Normal', 'Strong'],
        ['Overcast', 'Cool', 'Normal', 'Strong'],
        ['Sunny', 'Mild', 'High', 'Weak'],
        ['Sunny', 'Cool', 'Normal', 'Weak'],
        ['Rain', 'Mild', 'Normal', 'Weak'],
        ['Sunny', 'Mild', 'Normal', 'Strong'],
        ['Overcast', 'Mild', 'High', 'Strong'],
        ['Overcast', 'Hot', 'Normal', 'Weak'],
        ['Rain', 'Mild', 'High', 'Strong'],
        ['Overcast', 'Hot', 'High', 'Strong'],
        ['Overcast', 'Mild', 'High', 'Strong'],
        ['Overcast', 'Mild', 'Normal', 'Weak'],
        ['Rain', 'Mild', 'High', 'Strong'],
        ['Rain', 'Mild', 'Normal', 'Weak']], dtype=object),
 array(['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes',
        'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 

In [119]:
i = [i for i in range(len(X_n))]
i

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

In [120]:
rnd = []
y_rnd = []
for ind in np.random.choice(i, 30, True):
    rnd.append(X_n[ind])
    y_rnd.append(Y_n[ind])
rnd = np.array(rnd)
y_rnd = np.array(y_rnd)
rnd, y_rnd

(array([['Rain', 'Mild', 'High', 'Strong'],
        ['Rain', 'Cool', 'Normal', 'Strong'],
        ['Overcast', 'Hot', 'Normal', 'Weak'],
        ['Rain', 'Cool', 'Normal', 'Strong'],
        ['Overcast', 'Mild', 'High', 'Strong'],
        ['Overcast', 'Mild', 'Normal', 'Weak'],
        ['Sunny', 'Hot', 'High', 'Weak'],
        ['Overcast', 'Mild', 'Normal', 'Weak'],
        ['Overcast', 'Mild', 'Normal', 'Weak'],
        ['Overcast', 'Hot', 'Normal', 'Weak'],
        ['Rain', 'Cool', 'Normal', 'Strong'],
        ['Overcast', 'Hot', 'High', 'Strong'],
        ['Overcast', 'Hot', 'High', 'Strong'],
        ['Overcast', 'Hot', 'High', 'Weak'],
        ['Overcast', 'Mild', 'High', 'Strong'],
        ['Sunny', 'Mild', 'Normal', 'Strong'],
        ['Rain', 'Mild', 'High', 'Weak'],
        ['Sunny', 'Mild', 'High', 'Weak'],
        ['Sunny', 'Cool', 'Normal', 'Weak'],
        ['Overcast', 'Mild', 'High', 'Strong'],
        ['Overcast', 'Mild', 'High', 'Strong'],
        ['Rain', 'Mild', 'High

In [128]:
i = [i for i in range(X_n.shape[1])]
i

[0, 1, 2, 3]

In [183]:
fea = np.sort(np.random.choice(i, 2, False))
fea

array([0, 3])

In [184]:
samples = np.array([rnd[:,index] if index in fea else np.array(['' for index in range(rnd.shape[0])]) for index in i]).T
samples

array([['Rain', '', '', 'Strong'],
       ['Rain', '', '', 'Strong'],
       ['Overcast', '', '', 'Weak'],
       ['Rain', '', '', 'Strong'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Weak'],
       ['Sunny', '', '', 'Weak'],
       ['Overcast', '', '', 'Weak'],
       ['Overcast', '', '', 'Weak'],
       ['Overcast', '', '', 'Weak'],
       ['Rain', '', '', 'Strong'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Weak'],
       ['Overcast', '', '', 'Strong'],
       ['Sunny', '', '', 'Strong'],
       ['Rain', '', '', 'Weak'],
       ['Sunny', '', '', 'Weak'],
       ['Sunny', '', '', 'Weak'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Strong'],
       ['Rain', '', '', 'Weak'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Weak'],
       ['Sunny', '', '', 'Strong'],
       ['R

In [185]:
m = DecisionTreeClassifier()
m.fit(samples, y_rnd)
print(m.tree)

 | 0
....Overcast | 3
........Strong | Yes
........Weak | Yes
....Rain | 3
........Strong | No
........Weak | Yes
....Sunny | 3
........Strong | Yes
........Weak | No



In [186]:
m.score(samples, y_rnd)

0.8333333333333334

In [264]:
X.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety'], dtype='object')

In [10]:
mod = RandomForestClassifier(max_features=None)
mod.fit(X_train, Y_train)

model = DecisionTreeClassifier()
model.fit(X_train, Y_train)

In [11]:
mod.score(X_test, Y_test), model.score(X_test, Y_test)

(0.7777777777777778, 0.7754629629629629)

In [12]:
i = 330
mod.predict_proba(np.array(X_test)[i]), model.predict_proba(np.array(X_test)[i])

(array([0.56018659, 0.        , 0.43981341, 0.        ]),
 array([0.55555556, 0.        , 0.44444444, 0.        ]))

In [13]:
model.tree.classes

array(['acc', 'good', 'unacc', 'vgood'], dtype=object)

In [14]:
np.array(Y_test)[i]

'acc'

In [15]:
Y

0       unacc
1       unacc
2       unacc
3       unacc
4       unacc
        ...  
1723     good
1724    vgood
1725    unacc
1726     good
1727    vgood
Name: class values, Length: 1728, dtype: object

In [16]:
print(mod.forest[0].tree)

 | 5
....high | 0
........high | 1
............high | 4
................big | acc
................med | acc
................small | acc
............low | 4
................big | acc
................med | unacc
................small | unacc
............med | 4
................big | unacc
................med | acc
................small | acc
............vhigh | unacc
........low | 1
............high | 4
................big | vgood
................med | unacc
................small | acc
............low | 4
................big | vgood
................med | vgood
................small | good
............med | 4
................big | vgood
................med | vgood
................small | good
............vhigh | 4
................big | acc
................med | acc
................small | acc
........med | 1
............high | 4
................big | acc
................med | acc
................small | acc
............low | 4
................big | vgood
................med | vgood
......

In [17]:
from collections import Counter

In [18]:
Counter([tree.predict(np.array(X)[0]).item() for tree in mod.forest]).most_common(1)[0][0]

'unacc'

In [3]:
n = np.array([5, 2, 4])
n[np.argsort(n)]

array([2, 4, 5])

In [6]:
len(n[0])

TypeError: object of type 'numpy.int32' has no len()

In [39]:
df2 = pd.read_csv(os.path.join(os.getenv('workspaceFolder'),'star_classification.csv'))
df2

obj_ID       alpha      delta         u         g         r  \
0      1.237661e+18  135.689107  32.494632  23.87882  22.27530  20.39501   
1      1.237665e+18  144.826101  31.274185  24.77759  22.83188  22.58444   
2      1.237661e+18  142.188790  35.582444  25.26307  22.66389  20.60976   
3      1.237663e+18  338.741038  -0.402828  22.13682  23.77656  21.61162   
4      1.237680e+18  345.282593  21.183866  19.43718  17.58028  16.49747   
...             ...         ...        ...       ...       ...       ...   
99995  1.237679e+18   39.620709  -2.594074  22.16759  22.97586  21.90404   
99996  1.237679e+18   29.493819  19.798874  22.69118  22.38628  20.45003   
99997  1.237668e+18  224.587407  15.700707  21.16916  19.26997  18.20428   
99998  1.237661e+18  212.268621  46.660365  25.35039  21.63757  19.91386   
99999  1.237661e+18  196.896053  49.464643  22.62171  21.79745  20.60115   

              i         z  run_ID  rerun_ID  cam_col  field_ID   spec_obj_ID  \
0      19.16573  18.79371    3606       301        2        79  6.543777e+18   
1      21.16812  21.61427    4518       301        5       119  1.176014e+19   
2      19.34857  18.94827    3606       301        2       120  5.152200e+18   
3      20.50454  19.25010    4192       301        3       214  1.030107e+19   
4      15.97711  15.54461    8102       301        3       137  6.891865e+18   
...         ...       ...     ...       ...      ...       ...           ...   
99995  21.30548  20.73569    7778       301        2       581  1.055431e+19   
99996  19.75759  19.41526    7917       301        1       289  8.586351e+18   
99997  17.69034  17.35221    5314       301        4       308  3.112008e+18   
99998  19.07254  18.62482    3650       301        4       131  7.601080e+18   
99999  20.00959  19.28075    3650       301        4        60  8.343152e+18   

        class  redshift  plate    MJD  fiber_ID  
0      GALAXY  0.634794   5812  56354       171  
1      GALAXY  0.779136  10445  58158       427  
2      GALAXY  0.644195   4576  55592       299  
3      GALAXY  0.932346   9149  58039       775  
4      GALAXY  0.116123   6121  56187       842  
...       ...       ...    ...    ...       ...  
99995  GALAXY  0.000000   9374  57749       438  
99996  GALAXY  0.404895   7626  56934       866  
99997  GALAXY  0.143366   2764  54535        74  
99998  GALAXY  0.455040   6751  56368       470  
99999  GALAXY  0.542944   7410  57104       851  

[100000 rows x 18 columns]

In [147]:
df2_2 = df2.assign(quality = [str(x) for x in df2['cam_col']]).sample(1000)
df2_2

obj_ID       alpha      delta         u         g         r  \
86907  1.237662e+18  212.044581  50.580302  23.32264  21.92291  20.09829   
3365   1.237663e+18  320.549823   0.944258  23.26229  22.54610  21.91137   
65637  1.237679e+18    4.899961  17.289923  22.50280  21.95141  20.50931   
42362  1.237664e+18    2.511038  -0.327220  24.65245  23.53391  22.43094   
46904  1.237671e+18  130.234323  11.434219  22.51786  20.76506  19.01512   
...             ...         ...        ...       ...       ...       ...   
82026  1.237661e+18  152.412432  38.781498  25.34645  22.59161  20.85895   
34954  1.237679e+18   26.956960  18.049533  23.58017  22.38453  20.95751   
78325  1.237679e+18  328.900464   3.252099  21.89075  21.64397  21.29714   
24889  1.237653e+18  315.982472  10.166654  19.82951  18.47593  17.61983   
36471  1.237671e+18  119.875579   8.871728  19.21864  18.28391  18.00780   

              i         z  run_ID  rerun_ID  cam_col  field_ID   spec_obj_ID  \
86907  19.30005  18.80207    3918       301        6       118  7.595517e+18   
3365   21.25633  21.02185    4187       301        6        86  1.038657e+19   
65637  19.69548  19.25096    7713       301        3       262  6.963853e+18   
42362  22.23507  20.76109    4263       301        3       132  1.058592e+19   
46904  18.43756  18.07859    5935       301        3        91  5.952797e+18   
...         ...       ...     ...       ...      ...       ...           ...   
82026  19.86432  19.44096    3704       301        6       137  5.142206e+18   
34954  19.89369  19.56886    7913       301        2       128  5.762503e+18   
78325  21.23230  20.88194    7765       301        2       115  1.275537e+19   
24889  17.17385  16.89285    1749       301        4        96  8.186604e+17   
36471  17.91628  17.94948    5935       301        4        21  3.315793e+18   

        class  redshift  plate    MJD  fiber_ID quality  
86907  GALAXY  0.462306   6746  56386       713       6  
3365   GALAXY  0.742208   9225  58013       509       6  
65637  GALAXY  0.522231   6185  56217       591       3  
42362  GALAXY  1.146773   9402  58039       750       3  
46904  GALAXY  0.355923   5287  55952       596       3  
...       ...       ...    ...    ...       ...     ...  
82026  GALAXY  0.521992   4567  55589       804       6  
34954  GALAXY  0.610003   5118  55830       537       2  
78325     QSO  0.745747  11329  58426       181       2  
24889  GALAXY  0.139021    727  52207       477       4  
36471    STAR  0.001255   2945  54505        64       4  

[1000 rows x 19 columns]

In [148]:
X = df2_2.drop('class', axis=1)
Y = df2_2['class']

In [149]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [150]:
from treeModels.decision_algorithms import DecisionAlgorithm

In [151]:
mod = DecisionTreeClassifier(max_depth=10)

In [152]:
mod.fit(X_train, Y_train)

E:\Tomas\Desktop\Code\TPFinalAlgo2\src\treeModels\decision_algorithms.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return float(information_gain(col_values, Y)) / float(split_info(col_values, Y))


In [153]:
mod.score(X_test, Y_test)

0.94

In [154]:
mod = RandomForestClassifier(n_estimators = 10, max_depth=10, max_features=None)
mod.fit(X_train, Y_train)

KeyboardInterrupt: 

In [ ]:
mod.score(X_test, Y_test)

0.72

In [ ]:
model = SkDecisionTree()
model.fit(X_train, Y_train)

DecisionTreeClassifier()

In [ ]:
model.score(X_test, Y_test)

0.935

In [ ]:
model = SkRandomForest(n_estimators=20, max_depth=10)
model.fit(X_train, Y_train)

RandomForestClassifier(max_depth=10, n_estimators=20)

In [ ]:
model.score(X_test, Y_test)

0.955