$$ WIP $$

In [1]:
from treeModels import *
from sklearn.tree import DecisionTreeClassifier as SkDecisionTree
from sklearn.ensemble import RandomForestClassifier as SkRandomForest
import numpy as np
import pandas as pd
import os
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv(os.path.join(os.getenv('workspaceFolder'),'play_tennis.csv'))
df[df['outlook'] == 'Overcast']

outlook  temp humidity    wind play
2   Overcast   Hot     High    Weak  Yes
6   Overcast  Cool   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
14  Overcast   Hot     High  Strong   No
15  Overcast  Mild     High  Strong  Yes
16  Overcast  Mild   Normal    Weak  Yes

In [3]:
X = df.drop("play", axis=1)
Y = df['play']

In [5]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [6]:
X_test

outlook  temp humidity    wind
0      Sunny   Hot     High    Weak
11  Overcast  Mild     High  Strong
7      Sunny  Mild     High    Weak
9       Rain  Mild   Normal    Weak

In [6]:
model = DecisionTreeClassifier()
model.fit(X_train, Y_train)

In [7]:
model.get_depth()

5

In [9]:
print(model.tree)

 | 0
....Overcast | 1
........Cool | Yes
........Hot | 3
............Strong | No
............Weak | Yes
........Mild | Yes
....Rain | 3
........Strong | 1
............Cool | No
............Mild | Yes
........Weak | Yes
....Sunny | 2
........High | No
........Normal | Yes



In [11]:
model.predict_proba(['Rain', 'Hot', 'Normal', 'Strong'])

array([0.66666667, 0.33333333])

In [10]:
model.score(X_test, Y_test)

0.75

In [13]:
model.tree.forest['Rain'].forest['Strong'].get_class_proportion()

array([0.66666667, 0.33333333])

In [23]:
skmodel = SkDecisionTree(criterion='entropy')
skmodel.fit(X, Y)

ValueError: could not convert string to float: 'Sunny'

In [24]:
mod = DecisionTreeClassifier()
mod.fit(X, Y)

DecisionTreeClassifier(max_depth=inf, min_samples_split=2, min_samples_leaf=1, min_impurity_decrease=0.0, algorithm='ID3')

In [3]:
df2 = pd.read_csv(os.path.join(os.getenv('workspaceFolder'),'CarEval.csv'))
df2

buying  maint  doors persons lug_boot safety class values
0     vhigh  vhigh      2       2    small    low        unacc
1     vhigh  vhigh      2       2    small    med        unacc
2     vhigh  vhigh      2       2    small   high        unacc
3     vhigh  vhigh      2       2      med    low        unacc
4     vhigh  vhigh      2       2      med    med        unacc
...     ...    ...    ...     ...      ...    ...          ...
1723    low    low  5more    more      med    med         good
1724    low    low  5more    more      med   high        vgood
1725    low    low  5more    more      big    low        unacc
1726    low    low  5more    more      big    med         good
1727    low    low  5more    more      big   high        vgood

[1728 rows x 7 columns]

In [9]:
df2['persons'].unique()

array(['2', '4', 'more'], dtype=object)

In [4]:
df2_2 = df2.assign(doors = [int(x) if x != '5more' else 5 for x in df2['doors']])

In [5]:
df2_2 = df2_2.assign(persons = [int(x) if x != 'more' else 6 for x in df2['persons']])

In [14]:
df2_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   buying        1728 non-null   object
 1   maint         1728 non-null   object
 2   doors         1728 non-null   int64 
 3   persons       1728 non-null   int64 
 4   lug_boot      1728 non-null   object
 5   safety        1728 non-null   object
 6   class values  1728 non-null   object
dtypes: int64(2), object(5)
memory usage: 94.6+ KB


In [15]:
df2_2

buying  maint  doors  persons lug_boot safety class values
0     vhigh  vhigh      2        2    small    low        unacc
1     vhigh  vhigh      2        2    small    med        unacc
2     vhigh  vhigh      2        2    small   high        unacc
3     vhigh  vhigh      2        2      med    low        unacc
4     vhigh  vhigh      2        2      med    med        unacc
...     ...    ...    ...      ...      ...    ...          ...
1723    low    low      5        6      med    med         good
1724    low    low      5        6      med   high        vgood
1725    low    low      5        6      big    low        unacc
1726    low    low      5        6      big    med         good
1727    low    low      5        6      big   high        vgood

[1728 rows x 7 columns]

In [5]:
df2['doors'] = str(df2['doors'])
df2['persons'] = str(df2['persons'])

In [6]:
X = df2.drop('class values', axis=1)
Y = df2['class values']

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25)

In [12]:
model = DecisionTreeClassifier()
model.fit(X_train, Y_train)

In [13]:
model.get_depth()

5

In [14]:
model.score(X_train, Y_train)

0.8171296296296297

In [24]:
print(model.tree)

 | 5
....high | 0
........high | 1
............high | 4
................big | acc
................med | acc
................small | acc
............low | 4
................big | acc
................med | acc
................small | acc
............med | 4
................big | acc
................med | acc
................small | acc
............vhigh | unacc
........low | 1
............high | 4
................big | vgood
................med | vgood
................small | acc
............low | 4
................big | vgood
................med | vgood
................small | good
............med | 4
................big | vgood
................med | unacc
................small | good
............vhigh | 4
................big | acc
................med | acc
................small | acc
........med | 1
............high | 4
................big | acc
................med | unacc
................small | acc
............low | 4
................big | vgood
................med | vgood
..........

In [187]:
df

outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No
14  Overcast   Hot     High  Strong   No
15  Overcast  Mild     High  Strong  Yes
16  Overcast  Mild   Normal    Weak  Yes
17      Rain  Mild     High  Strong  Yes
18      Rain  Mild   Normal    Weak   No

In [74]:
X_n = np.array(X)
Y_n = np.array(Y)
X_n, Y_n

(array([['Sunny', 'Hot', 'High', 'Weak'],
        ['Sunny', 'Hot', 'High', 'Strong'],
        ['Overcast', 'Hot', 'High', 'Weak'],
        ['Rain', 'Mild', 'High', 'Weak'],
        ['Rain', 'Cool', 'Normal', 'Weak'],
        ['Rain', 'Cool', 'Normal', 'Strong'],
        ['Overcast', 'Cool', 'Normal', 'Strong'],
        ['Sunny', 'Mild', 'High', 'Weak'],
        ['Sunny', 'Cool', 'Normal', 'Weak'],
        ['Rain', 'Mild', 'Normal', 'Weak'],
        ['Sunny', 'Mild', 'Normal', 'Strong'],
        ['Overcast', 'Mild', 'High', 'Strong'],
        ['Overcast', 'Hot', 'Normal', 'Weak'],
        ['Rain', 'Mild', 'High', 'Strong'],
        ['Overcast', 'Hot', 'High', 'Strong'],
        ['Overcast', 'Mild', 'High', 'Strong'],
        ['Overcast', 'Mild', 'Normal', 'Weak'],
        ['Rain', 'Mild', 'High', 'Strong'],
        ['Rain', 'Mild', 'Normal', 'Weak']], dtype=object),
 array(['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes',
        'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 

In [119]:
i = [i for i in range(len(X_n))]
i

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

In [120]:
rnd = []
y_rnd = []
for ind in np.random.choice(i, 30, True):
    rnd.append(X_n[ind])
    y_rnd.append(Y_n[ind])
rnd = np.array(rnd)
y_rnd = np.array(y_rnd)
rnd, y_rnd

(array([['Rain', 'Mild', 'High', 'Strong'],
        ['Rain', 'Cool', 'Normal', 'Strong'],
        ['Overcast', 'Hot', 'Normal', 'Weak'],
        ['Rain', 'Cool', 'Normal', 'Strong'],
        ['Overcast', 'Mild', 'High', 'Strong'],
        ['Overcast', 'Mild', 'Normal', 'Weak'],
        ['Sunny', 'Hot', 'High', 'Weak'],
        ['Overcast', 'Mild', 'Normal', 'Weak'],
        ['Overcast', 'Mild', 'Normal', 'Weak'],
        ['Overcast', 'Hot', 'Normal', 'Weak'],
        ['Rain', 'Cool', 'Normal', 'Strong'],
        ['Overcast', 'Hot', 'High', 'Strong'],
        ['Overcast', 'Hot', 'High', 'Strong'],
        ['Overcast', 'Hot', 'High', 'Weak'],
        ['Overcast', 'Mild', 'High', 'Strong'],
        ['Sunny', 'Mild', 'Normal', 'Strong'],
        ['Rain', 'Mild', 'High', 'Weak'],
        ['Sunny', 'Mild', 'High', 'Weak'],
        ['Sunny', 'Cool', 'Normal', 'Weak'],
        ['Overcast', 'Mild', 'High', 'Strong'],
        ['Overcast', 'Mild', 'High', 'Strong'],
        ['Rain', 'Mild', 'High

In [128]:
i = [i for i in range(X_n.shape[1])]
i

[0, 1, 2, 3]

In [183]:
fea = np.sort(np.random.choice(i, 2, False))
fea

array([0, 3])

In [184]:
samples = np.array([rnd[:,index] if index in fea else np.array(['' for index in range(rnd.shape[0])]) for index in i]).T
samples

array([['Rain', '', '', 'Strong'],
       ['Rain', '', '', 'Strong'],
       ['Overcast', '', '', 'Weak'],
       ['Rain', '', '', 'Strong'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Weak'],
       ['Sunny', '', '', 'Weak'],
       ['Overcast', '', '', 'Weak'],
       ['Overcast', '', '', 'Weak'],
       ['Overcast', '', '', 'Weak'],
       ['Rain', '', '', 'Strong'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Weak'],
       ['Overcast', '', '', 'Strong'],
       ['Sunny', '', '', 'Strong'],
       ['Rain', '', '', 'Weak'],
       ['Sunny', '', '', 'Weak'],
       ['Sunny', '', '', 'Weak'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Strong'],
       ['Rain', '', '', 'Weak'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Strong'],
       ['Overcast', '', '', 'Weak'],
       ['Sunny', '', '', 'Strong'],
       ['R

In [185]:
m = DecisionTreeClassifier()
m.fit(samples, y_rnd)
print(m.tree)

 | 0
....Overcast | 3
........Strong | Yes
........Weak | Yes
....Rain | 3
........Strong | No
........Weak | Yes
....Sunny | 3
........Strong | Yes
........Weak | No



In [186]:
m.score(samples, y_rnd)

0.8333333333333334

In [264]:
X.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety'], dtype='object')

In [10]:
mod = RandomForestClassifier(max_features=None)
mod.fit(X_train, Y_train)

model = DecisionTreeClassifier()
model.fit(X_train, Y_train)

In [11]:
mod.score(X_test, Y_test), model.score(X_test, Y_test)

(0.7777777777777778, 0.7754629629629629)

In [12]:
i = 330
mod.predict_proba(np.array(X_test)[i]), model.predict_proba(np.array(X_test)[i])

(array([0.56018659, 0.        , 0.43981341, 0.        ]),
 array([0.55555556, 0.        , 0.44444444, 0.        ]))

In [13]:
model.tree.classes

array(['acc', 'good', 'unacc', 'vgood'], dtype=object)

In [14]:
np.array(Y_test)[i]

'acc'

In [15]:
Y

0       unacc
1       unacc
2       unacc
3       unacc
4       unacc
        ...  
1723     good
1724    vgood
1725    unacc
1726     good
1727    vgood
Name: class values, Length: 1728, dtype: object

In [16]:
print(mod.forest[0].tree)

 | 5
....high | 0
........high | 1
............high | 4
................big | acc
................med | acc
................small | acc
............low | 4
................big | acc
................med | unacc
................small | unacc
............med | 4
................big | unacc
................med | acc
................small | acc
............vhigh | unacc
........low | 1
............high | 4
................big | vgood
................med | unacc
................small | acc
............low | 4
................big | vgood
................med | vgood
................small | good
............med | 4
................big | vgood
................med | vgood
................small | good
............vhigh | 4
................big | acc
................med | acc
................small | acc
........med | 1
............high | 4
................big | acc
................med | acc
................small | acc
............low | 4
................big | vgood
................med | vgood
......

In [17]:
from collections import Counter

In [18]:
Counter([tree.predict(np.array(X)[0]).item() for tree in mod.forest]).most_common(1)[0][0]

'unacc'

In [3]:
n = np.array([5, 2, 4])
n[np.argsort(n)]

array([2, 4, 5])

In [6]:
len(n[0])

TypeError: object of type 'numpy.int32' has no len()

In [2]:
df2 = pd.read_csv(os.path.join(os.getenv('workspaceFolder'),'CarEval.csv'))
df2

buying  maint  doors persons lug_boot safety class values
0     vhigh  vhigh      2       2    small    low        unacc
1     vhigh  vhigh      2       2    small    med        unacc
2     vhigh  vhigh      2       2    small   high        unacc
3     vhigh  vhigh      2       2      med    low        unacc
4     vhigh  vhigh      2       2      med    med        unacc
...     ...    ...    ...     ...      ...    ...          ...
1723    low    low  5more    more      med    med         good
1724    low    low  5more    more      med   high        vgood
1725    low    low  5more    more      big    low        unacc
1726    low    low  5more    more      big    med         good
1727    low    low  5more    more      big   high        vgood

[1728 rows x 7 columns]

In [3]:
df2_2 = df2.assign(doors = [int(x) if x != '5more' else 5 for x in df2['doors']])
df2_2 = df2_2.assign(persons = [int(x) if x != 'more' else 6 for x in df2['persons']])

In [4]:
X = df2_2.drop('class values', axis=1)
Y = df2_2['class values']

In [101]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [5]:
from treeModels.decision_algorithms import DecisionAlgorithm

In [102]:
mod = DecisionTreeClassifier(max_depth= 10, algorithm=DecisionAlgorithm.C45)

In [103]:
mod.fit(X_train, Y_train)

E:\Tomas\Desktop\Code\TPFinalAlgo2\src\treeModels\decision_algorithms.py:104: RuntimeWarning: invalid value encountered in scalar divide
  return information_gain(col_values, Y) / split_info(col_values, Y)


In [8]:
print(mod.tree)

 | [persons]
....<=3.0 | unacc
....>3.0 | [safety]
........high | [buying]
............high | acc
............low | vgood
............med | acc
............vhigh | unacc
........low | unacc
........med | [buying]
............high | unacc
............low | acc
............med | acc
............vhigh | unacc



In [104]:
mod.score(X_test, Y_test)

0.9335260115606936

In [12]:
mod = DecisionTreeClassifier(algorithm=DecisionAlgorithm.C45)
mod.fit(X, Y)

In [107]:
mod = RandomForestClassifier(n_estimators = 50, max_depth=10, algorithm=DecisionAlgorithm.C45, max_features=None)
mod.fit(X_train, Y_train)

In [108]:
mod.score(X_test, Y_test)

0.953757225433526

In [109]:
print(mod.forest[1].tree)

 | [safety]
....high | [persons]
........<=3.0 | unacc
........>3.0 | [buying]
............high | [maint]
................high | [lug_boot]
....................big | acc
....................med | acc
....................small | [doors]
........................<=2.5 | [persons]
............................<=5.0 | acc
............................>5.0 | unacc
........................>2.5 | acc
................low | acc
................med | [lug_boot]
....................big | acc
....................med | acc
....................small | [doors]
........................<=2.5 | unacc
........................>2.5 | acc
................vhigh | unacc
............low | [maint]
................high | [lug_boot]
....................big | vgood
....................med | [doors]
........................<=4.0 | acc
........................>4.0 | vgood
....................small | [doors]
........................<=2.5 | [persons]
............................<=5.0 | acc
............................>5.